inherit_gem:
  niftany: niftany_rubocop.yml

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/jobs/remediation_job.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/jobs/remediation_job.rb'

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/20250714203038_create_gui_users.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

# Rubocop doesn't seem to understand the rswag DSL
# Exclude the rswag spec file from RSpec/EmptyExampleGroup and
# be careful because the unsafe autocorrect will delete everything
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/v1/api-docs/jobs_spec.rb'

RSpec/VariableName:
  Exclude:
    - 'spec/requests/api/v1/api-docs/jobs_spec.rb'