inherit_gem:
  niftany: niftany_rubocop.yml

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false