x-web_env: &web_env
  environment:
      REDIS_PASSWORD: redis_password
      API_BEARER_TOKEN: 
      MYSQL_DB: pdf_accessibility_api
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_HOST: db
services:
  web:
    user: 1000:1000
    depends_on:
      - db
    tty: true
    stdin_open: true
    <<: *web_env
    build:
      context: .
      target: dev
    volumes:
    - bundle-data:/app/vendor/bundle
    - node-data:/app/node_modules
    - type: bind
      source: ./
      target: /app
    ports:
      - "3000:3000"
  db:
    environment:
      MYSQL_ROOT_PASSWORD: pdf_accessibility_api
      MYSQL_DATABASE: pdf_accessibility_api
      MYSQL_USER: pdf_accessibility_api
      MYSQL_PASSWORD: pdf_accessibility_api
    image: mariadb:10.4.6
    ports:
    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
  # redis:
  #   image: redis:7.0.12
  #   volumes:
  #   - redis-data:/data
  #   ports:
  #   - "6379:6379"
  # minio:
  #   image: minio/minio:RELEASE.2021-03-17T02-33-02Z
  #   container_name: minio
  #   restart: always
  #   volumes:
  #   - minio-data:/data
  #   environment:
  #     MINIO_ACCESS_KEY:
  #     MINIO_SECRET_KEY:
  #     MINIO_ROOT_USER:
  #     MINIO_ROOT_PASSWORD:
  #   ports:
  #   - ${MINIO_PORT:-9000}:9000 # API
  #   entrypoint:
  #   - /bin/sh
  #   - -c
  #   - mkdir -p /data/pdf_accessibility_api; minio --compat server --address ':9000' /data
    
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  redis-data:
  bundle-data:
  node-data:
  minio-data:
  db-data:
