x-web_env: &web_env
  environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: redispassword
      API_BEARER_TOKEN: 
      MYSQL_DB: pdf_accessibility_api
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_HOST: db
services:
  web:
    user: 1000:1000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    tty: true
    stdin_open: true
    <<: *web_env
    build:
      context: .
      target: dev
    volumes:
    - bundle-data:/app/vendor/bundle
    - node-data:/app/node_modules
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -f http://localhost:3000/
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  worker:
    user: 1000:1000
    depends_on:
      web:
        condition: service_healthy
    <<: *web_env
    build:
      context: .
      target: dev-worker
    volumes:
      - worker-bundle-data:/app/vendor/bundle
  db:
    environment:
      MYSQL_ROOT_PASSWORD: pdf_accessibility_api
      MYSQL_DATABASE: pdf_accessibility_api
      MYSQL_USER: pdf_accessibility_api
      MYSQL_PASSWORD: pdf_accessibility_api
    image: mariadb:10.4.6
    ports:
    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:8.0.2
    command: redis-server --requirepass redispassword
    volumes:
    - redis-data:/data
    ports:
    - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    container_name: minio
    restart: always
    volumes:
    - minio-data:/data
    environment:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
    ports:
    - ${MINIO_PORT:-9000}:9000 # API
    entrypoint:
    - /bin/sh
    - -c
    - mkdir -p /data/pdf_accessibility_api; minio --compat server --address ':9000' /data
    
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  redis-data:
  bundle-data:
  worker-bundle-data:
  node-data:
  minio-data:
  db-data:
