development:
  adapter: redis
  url: <%= ENV.fetch("ACTION_CABLE_REDIS_URL")  { "redis://localhost:6379/1" }%>
  channel_prefix: pdf_accessibility_api_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("ACTION_CABLE_REDIS_URL")  { "redis://redis:6379/1" }%>
  channel_prefix: pdf_accessibility_api_production
