development:
  adapter: redis
  url: <%= "redis://:#{ENV.fetch('REDIS_PASSWORD', 'redispassword')}@#{ENV.fetch('REDIS_HOST', 'localhost')}:#{ENV.fetch('REDIS_PORT', '6379')}/1" %>
  channel_prefix: pdf_accessibility_api_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://:#{ENV.fetch('REDIS_PASSWORD', 'redispassword')}@#{ENV.fetch('REDIS_HOST', 'localhost')}:#{ENV.fetch('REDIS_PORT', '6379')}/1" %>
  channel_prefix: pdf_accessibility_api_production
