development:
  adapter: redis
  url: <%= redis_url(1) %>
  channel_prefix: pdf_accessibility_api_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= redis_url(1) %>
  channel_prefix: pdf_accessibility_api_production