development:
  adapter: redis
  url: <%= redis_url(ACTION_CABLE_REDIS_DB) %>
  channel_prefix: pdf_accessibility_api_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= redis_url(ACTION_CABLE_REDIS_DB) %>
  channel_prefix: pdf_accessibility_api_production